name: '– Brook Riggio – '
analytics: {}
github: true
author:
  name: Brook Riggio
  url: brook.rigg.io
  email: brook@rigg.io
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
layout_spectrum: 0.0008380073122680187
color:
  lightness: 0.56149881798774
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  saturation: 0.7514057792723179
  brandStrength: 0.1238177374470979
  rhythmicContrast: 0.9651455511339009
content_rating:
  adult: false
typography_spectrum: 0.9833828972186893
opengraph: {}
title: Brook's Blog
